name: CI Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        id: dependency
        run: |
          python -m pip install --upgrade pip
	  pip install -r requirements.txt

      - name: Lint with flake8
        id: lint
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
	  flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        id: nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
          
